[indexing]
demangle-names = true
index-relocations = false
min-symbol-size = 1
use-dwarfdump = true
exclude = ["**/*.so"]
extra-globs = ["/usr/lib/x86_64-linux-gnu/libc*.so*"]

[arch.default]
addr2line = "addr2line"
dwarfdump = "dwarfdump"

disassembler = "objdump"
disassembler-args = "-dC --no-show-raw-insn '{path}' --section '{section}' --start-address 0x{address:x} --stop-address 0x{endaddress:x}"

[arch.CUDA]
addr2line = "/bin/false"
disassembler = "cuobjdump"
disassembler-args = "--dump-sass '{path}' --function '{name}'"

[arch.X86_64]
disassembler = "objdump -M intel"

# It's possible to override settings for any directory too
[path."/src/path/to/some/dir/"]
arch.default.addr2line = "special-addr2line"
indexing.index-relocations = true
indexing.exclude = ["**/build/stage1-*/**"]
